module.exports = {
  "typescript": "ts",
  "@angular/animations": "ng.animations",
  "@angular/core": "ng.core",
  "@angular/common": "ng.common",
  "@angular/common/http": "ng.common",
  "@angular/http": "ng.http",
  "@angular/forms": "ng.forms",
  "@angular/platform-browser": "ng.platform-browser",
  "@angular/platform-browser/animations": "ng.platform-browser.animations",
  "@angular/router": "ng.router",
  "moment": "moment",
  "rxjs/observable/combineLatest": "Rx",
  "rxjs/observable/of": "Rx",
  "rxjs/operators": "Rx",
  "rxjs/BehaviorSubject": "Rx",
  "rxjs/Observable": "Rx",
  "rxjs/Subject": "Rx",
  "rxjs/Subscription": "Rx"
};
